[appendix]
== 専門用語/Terminology
=== ボールの操作/Ball Manipulation
シュートと<<ドリブルデバイス/Dribbling Device, ドリブル>>はボールの操作とみなされ、ボールが機体で跳ね返った場合は操作とはみなさない。 +
Shooting and <<ドリブルデバイス/Dribbling Device, dribbling>> is considered as manipulating the ball, the ball accidentally bouncing off the hull is not.

[appendix]
== ゲームイベント表/Game Event Table
ゲームイベント表は、各ゲームイベントとその結果をまとめたものである。また、<<オートレフ/Automatic Referee, オートレフ>>の実装が処理できなければならないものを表記する。 +
The game event table is a compilation of the different game events and their consequences. It also lists what all <<オートレフ/Automatic Referee, Automatic Referee>> implementations must be capable of handling.

NOTE: この表にまとめられた情報は不完全なものである。すべての定義を確認するには、対応した各章を読むこと。 +
Note that the information shown in this table here is incomplete. Please read the sections of the respective events for the full definitions.

=== フィールド外にボールが出た際のイベント/Events For Ball Leaving The Field
|===
| イベント /Event | 適用範囲 /Applicability | 実行されるコマンド /Command | 処理担当 /Handled by

| <<Touch Line Crossing>> | <<Ball In And Out Of Play, ball in play>> | <<Stop>> -> <<Free Kick>> | auto referee
| <<Goal Line Crossing>> | <<Ball In And Out Of Play, ball in play>> | <<Stop>> -> <<Free Kick>> | auto referee

| <<aimless-kick, エイムレスキック>> +
<<aimless-kick, Aimless Kick>>
| <<インプレイとアウトオブプレイ/Ball In And Out Of Play, インプレイ>> +
<<インプレイとアウトオブプレイ/Ball In And Out Of Play, ball in play>>
| <<停止/Stop, ストップ>> -> <<フリーキック/Free Kick, フリーキック>> +
<<停止/Stop, Stop>> -> <<フリーキック/Free Kick, Free Kick>>
| オートレフ +
auto referee
|===


=== 試合の停止を伴うファウルに関するイベント/Events For Stopping Fouls
全ての<<試合の停止を伴うファウル/Stopping Fouls, 試合の停止を伴うファウル>>は次の結果をもたらす: +
All <<試合の停止を伴うファウル/Stopping Fouls, Stopping Fouls>> result in:

* ファウルのカウンターをひとつ増加させる(<<マルチプルディフェンス/Multiple Defenders, マルチプルディフェンス>>を除く)。 +
Incrementing the foul counter (except for <<マルチプルディフェンス/Multiple Defenders, Multiple Defenders>>).

|===
| イベント /Event | 適用範囲 /Applicability | アクション /Action | 処理担当 /Handled by

| <<ロボットの相手ディフェンスエリアへの極端な接近/Robot Too Close To Opponent Defense Area, ロボットの相手ディフェンスエリアへの極端な接近>> +
<<ロボットの相手ディフェンスエリアへの極端な接近/Robot Too Close To Opponent Defense Area, Robot Too Close To Opponent Defense Area>>
| <<停止/Stop, ストップ中>>、ならびに<<フリーキック/Free Kick, フリーキック中>> +
during <<停止/Stop, Stop>> and <<フリーキック/Free Kick, Free Kick>>
| <<停止/Stop, ストップ>> -> <<フリーキック/Free Kick, フリーキック>> +
<<停止/Stop, Stop>> -> <<フリーキック/Free Kick, Free Kick>>
| オートレフ +
auto referee

| <<マルチプルディフェンス/Multiple Defenders, マルチプルディフェンス>> +
<<マルチプルディフェンス/Multiple Defenders, Multiple Defenders>> +
| <<インプレイとアウトオブプレイ/Ball In And Out Of Play, インプレイ>> +
<<インプレイとアウトオブプレイ/Ball In And Out Of Play, ball in play>>
| <<停止/Stop, ストップ>> -> <<ペナルティーキック/Penalty Kick, ペナルティーキック>> +
<<停止/Stop, Stop>> -> <<ペナルティーキック/Penalty Kick, Penalty Kick>>
| オートレフ +
auto referee

| <<境界線との交差/Boundary Crossing, 境界線との交差>> +
<<境界線との交差/Boundary Crossing, Boundary Crossing>>
| <<インプレイとアウトオブプレイ/Ball In And Out Of Play, インプレイ>> +
<<インプレイとアウトオブプレイ/Ball In And Out Of Play, ball in play>>
| <<停止/Stop, ストップ>> -> <<フリーキック/Free Kick, フリーキック>> +
<<停止/Stop, Stop>> -> <<フリーキック/Free Kick, Free Kick>>
| オートレフ +
auto referee

| <<ディフェンスエリア/Defense Area, ディフェンスエリア>>内での<<キーパーによるボール保持/Keeper Held Ball, キーパーによるボール保持>> +
<<キーパーによるボール保持/Keeper Held Ball, Keeper Held Ball>> in <<ディフェンスエリア/Defense Area, defense area>>
| <<インプレイとアウトオブプレイ/Ball In And Out Of Play, インプレイ>> +
<<インプレイとアウトオブプレイ/Ball In And Out Of Play, ball in play>>
| <<停止/Stop, ストップ>> -> <<フリーキック/Free Kick, フリーキック>> +
<<停止/Stop, Stop>> -> <<フリーキック/Free Kick, Free Kick>>
| オートレフ +
game controller

| <<ドリブルの超過/Excessive Dribbling, オーバードリブル>> +
<<ドリブルの超過/Excessive Dribbling, Excessive Dribbling>>
| <<インプレイとアウトオブプレイ/Ball In And Out Of Play, インプレイ>> +
<<インプレイとアウトオブプレイ/Ball In And Out Of Play, ball in play>>
| <<停止/Stop, ストップ>> -> <<フリーキック/Free Kick, フリーキック>> +
<<停止/Stop, Stop>> -> <<フリーキック/Free Kick, Free Kick>>
| オートレフ +
auto referee

| <<プッシング/Pushing, プッシング>> +
<<プッシング/Pushing, Pushing>>
| 常時 +
always
| <<停止/Stop, ストップ>> -> <<フリーキック/Free Kick, フリーキック>> +
<<停止/Stop, Stop>> -> <<フリーキック/Free Kick, Free Kick>>
| 主審 -> game controller +
referee -> game controller

| <<ボールの保持/Ball Holding, ボールの保持>> +
<<ボールの保持/Ball Holding, Ball Holding>>
| <<インプレイとアウトオブプレイ/Ball In And Out Of Play, インプレイ>> +
<<インプレイとアウトオブプレイ/Ball In And Out Of Play, ball in play>>
| <<停止/Stop, ストップ>> -> <<フリーキック/Free Kick, フリーキック>> +
<<停止/Stop, Stop>> -> <<フリーキック/Free Kick, Free Kick>>
| 主審 -> game controller +
referee -> game controller

| <<転倒や部品の脱落/Tipping Over Or Dropping Parts, 転倒や部品の脱落>> +
<<転倒や部品の脱落/Tipping Over Or Dropping Parts, Tipping Over Or Dropping Parts>>
| 常時 +
always
| <<停止/Stop, ストップ>> -> <<フリーキック/Free Kick, フリーキック>> +
<<停止/Stop, Stop>> -> <<フリーキック/Free Kick, Free Kick>>
| 主審 -> game controller +
referee -> game controller
|===


=== 試合の停止を伴わないファウルに関するイベント/Events For Non Stopping Fouls
全ての<<試合の停止を伴わないファウル/Non Stopping Fouls, 試合の停止を伴わないファウル>>は以下の結果をもたらす: +
All <<試合の停止を伴わないファウル/Non Stopping Fouls, Non Stopping Fouls>> result in:

* ファウルのカウンターをひとつ増加させる。 +
Incrementing the foul counter.
* 中断することなく続いている場合、2秒ごとに繰り返される。 +
Repeated every 2 seconds, if still committed without interruption.

|===
| イベント /Event | 適用範囲 /Applicability | アクション /Action | 処理担当 /Handled by

| <<相手ディフェンスエリア内でのアタッカーのボールへの接触/Attacker Touched Ball In Opponent Defense Area, 相手ディフェンスエリア内でのボールへの接触>> +
<<相手ディフェンスエリア内でのアタッカーのボールへの接触/Attacker Touched Ball In Opponent Defense Area, Attacker Touched Ball In Opponent Defense Area>>
| <<インプレイとアウトオブプレイ/Ball In And Out Of Play, インプレイ中>> +
<<インプレイとアウトオブプレイ/Ball In And Out Of Play, ball in play>>
| - | オートレフ +
auto referee

| <<ボール速度/Ball Speed, ボール速度>> +
<<ボール速度/Ball Speed, Ball Speed>>
| <<インプレイとアウトオブプレイ/Ball In And Out Of Play, インプレイ中>> +
<<インプレイとアウトオブプレイ/Ball In And Out Of Play, ball in play>>
| - | オートレフ +
auto referee

| <<衝突/Crashing, 衝突>> +
<<衝突/Crashing,Crashing>>
| 常時 +
always
| - | オートレフ +
auto referee

| 双方による<<衝突/Crashing, 衝突>> +
<<衝突/Crashing, Crashing>> draw
| 常時 +
always
| - | オートレフ +
auto referee
|===


=== アウトオブプレイ中のファウルに関するイベント/Events For Fouls While Ball Out Of Play
全ての<<アウトオブプレイ中のファウル/Fouls While Ball Out Of Play, アウトオブプレイ中のファウル>>は以下の結果をもたらす: +
All <<アウトオブプレイ中のファウル/Fouls While Ball Out Of Play,Fouls While Ball Out Of Play>> result in:

* ファウルのカウンターをひとつ増加させる。 +
Incrementing the foul counter.
* 中断することなく続いている場合、2秒ごとに繰り返される。 +
Repeated every 2 seconds, if still committed.
* 各ファウル、チームに対し2秒間に一度のみ適用する。 +
Only once per foul, team and 2 seconds. +

|===
| イベント /Event | 適用範囲 /Applicability | アクション /Action | 処理担当 /Handled by

| <<ディフェンダーのボールへの極端な接近/Defender Too Close To Ball, ディフェンダーのボールへの極端な接近>> +
<<ディフェンダーのボールへの極端な接近/Defender Too Close To Ball, Defender Too Close To Ball>>
| <<インプレイとアウトオブプレイ/Ball In And Out Of Play, アウトオブプレイ中>> +
<<インプレイとアウトオブプレイ/Ball In And Out Of Play, ball out of play>>
| timer for bringing the ball into play is reset
| オートレフ +
auto referee

| <<ストップ中のロボットの速度/Robot Stop Speed, ストップ中のロボットの速度>> +
<<ストップ中のロボットの速度/Robot Stop Speed, Robot Stop Speed>>
| <<停止/Stop, ストップゲーム>>中 +
during <<停止/Stop, Stop>>
| -
| オートレフ +
auto referee

| <<ボール配置への干渉/Ball Placement Interference, ボール配置への干渉>> +
<<ボール配置への干渉/Ball Placement Interference, Ball Placement Interference>>
| <<ボール配置/Ball Placement, ボール配置>>中 +
during <<ボール配置/Ball Placement, Ball Placement>>
| 配置可能時間の延長(10秒) +
placement timer increased by 10 seconds
| オートレフ +
auto referee
|===


=== Events For Scoring Goals
|===
| Event | Applicability | Command | Handled By

| <<Scoring Goals, Possible Goal>> | <<Ball In And Out Of Play, ball in play>> | <<Halt>> | auto referee
| <<Scoring Goals, Goal>> | <<Ball In And Out Of Play, ball in play>> | <<Stop>> -> <<Kick-Off>> | referee -> game controller
| <<Scoring Goals, Invalid Goal>> | <<Ball In And Out Of Play, ball in play>> | <<Stop>> -> <<Free Kick>> | game controller
|===


=== Other events

|===
| Event | Applicability | Command | Handled By

| <<Double Touch>> | <<Ball In And Out Of Play, ball in play>> | <<Stop>> -> <<Free Kick>> | auto referee
| <<Ball Placement>> successful | during <<Ball Placement>> | continue | auto referee
| <<Penalty Kick>> failed | during <<Penalty Kick>> | <<Stop>> -> <<Free Kick>> | auto referee, game controller

| <<No Progress In Game>> | <<Ball In And Out Of Play, ball in play>> | <<Stop>> -> <<Force Start>> | game controller
| <<Ball Placement>> failed by team in favor | during <<Ball Placement>> | <<Stop>> -> <<Free Kick>> (div A) / previous command (div B) | game controller
| <<Ball Placement>> failed by opponent | during <<Ball Placement>> | <<Stop>> | game controller
| Multiple <<Fouls>> | always | <<Yellow Card>> | game controller
| Multiple <<Yellow Card, Yellow Cards>> | always | <<Red Card>> | game controller
| Perform manual <<Robot Substitution>> | during <<Stop>> | <<Halt>> (after next stoppage), then <<Stop>> | game controller
| <<Number Of Robots>> exceeded | always | <<Stop>> | game controller
| Raise <<Challenge Flags, Challenge flag>> | always | <<Stop>> | remote control -> game controller
| Perform <<Emergency stop>> | always | <<Halt>> | remote control -> game controller

| <<Unsporting Behavior>> | always | <<Stop>> -> <<Yellow Card>>, <<Red Card>>, <<Penalty Kick>>, <<Forced Forfeit>> or <<Disqualification>> | referee -> game controller
|===


[appendix]
== 各種時間の概要/Overview of Timings
|===
| 状況/Situation | ディヴィジョンAの時間/Div A Time | ディヴィジョンBの時間/Div B Time

| <<イエローカード/Yellow Card, イエローカード>>によるロボット除去 +
Remove robot for <<イエローカード/Yellow Card, Yellow Card>>
| 10 s       | 10 s

| <<ペナルティーキック/Penalty Kick, ペナルティーキック>> +
<<ペナルティーキック/Penalty Kick, penalty kick>>
| 10 s       | 10 s

| <<キックオフ/Kick-Off, キックオフ>> +
<<キックオフ/Kick-Off, kick-off>>
| 10 s       | 10 s

| <<フリーキック/Free Kick, フリーキック>> +
<<フリーキック/Free Kick, free kick>>
|  5 s       | 10 s

| <<ディフェンスエリア/Defense Area, ディフェンスエリア>>内での<<キーパーによるボール保持/Keeper Held Ball, キーパーによるボール保持>> +
<<キーパーによるボール保持/Keeper Held Ball, Keeper Held Ball>> inside <<ディフェンスエリア/Defense Area, Defense Area>>
|  5 s       | 10 s

| <<試合の停滞/No Progress In Game, 試合の停滞>> +
<<試合の停滞/No Progress In Game, No Progress In Game>>
|  5 s       | 10 s
|===


[appendix]
== ディヴィジョンごとの違い/Differences Between Divisions

これは、<<ディヴィジョン/Divisions, ディヴィジョン>>Aと<<ディヴィジョン/Divisions, ディヴィジョン>>Bの違いの完全なリストである。 +
This is a complete list of differences between <<ディヴィジョン/Divisions, division>> A and <<ディヴィジョン/Divisions, division>> B.

* ディヴィジョンAはディヴィジョンBよりも<<フィールドの大きさ/Dimensions, 大きなフィールド>>と<<ゴール/Goals, 大きなゴール>>で試合を行う。その結果、<<シュートアウト/Shoot-Out, シュートアウト>>もより遠くから行われる。 +
Division A plays on a <<フィールドの大きさ/Dimensions, larger field>> with <<ゴール/Goals, larger goals>> than division B. As a result, the <<シュートアウト/Shoot-Out, shoot-out>> is taken from a greater distance as well.
* ディヴィジョンAはディヴィジョンBよりも<<ロボットの台数/Number Of Robots, 多いロボット>>で試合を行う。 +
Division A plays with <<ロボットの台数/Number Of Robots, more robots>> than division B.
* <<ボール配置/Ball Placement, ボール配置>>の手順はディヴィジョンAでは必須であり、ディヴィジョンBでは任意である。 +
The automatic <<ボール配置/Ball Placement, ball placement>> procedure is mandatory for division A and optional for division B.
* <<aimless-kick, エイムレスキック>>のルールはディヴィジョンBにのみ適用される。 +
The <<aimless-kick, aimless kick>> rule only applies to division B.
* ディヴィジョンAはいくつかの状況における時間切れまでの時間が短い。 +
Division A has shorter timeouts in some situations
