== リーグ概要/League Overview
=== 委員会/Committees
(ロボカップの他のリークと同じように) 小型機リーグは3つの異なる委員会(実行委員会/executive committee,技術委員会/technical committee, 組織委員会/organizing committee)で運営されている。これらの委員会はそれぞれ異なる責任を持っている。各委員会の委員はRoboCup Small Size Leagueの公式ウェブサイト(https://ssl.robocup.org) で確認できる。 +
The Small Size League (like every other league of the RoboCup) is run by close cooperation of three different committees (<<Executive Committee, executive committee>>, <<Technical Committee, technical committee>> and <<Organizing Committee, organizing committee>>), all with a different set of responsibilities. The members of the respective committees can be found on the official RoboCup Small Size League website (https://ssl.robocup.org).

NOTE: 実際には、技術委員会と組織委員会に厳密な区別はない。各委員会の委員が協力して業務をこなしている。 +
In practice, there is no strict separation between the <<Technical Committee, technical>> and the <<Organizing Committee, organizing committee>>. Members of both committees often work together on the joint set of tasks.

それに加えて、地域の組織委員会/local organizing committeeの委員がRoboCupのすべてのリーグのイベントを整備している。 +
Additionally, the members of the <<Local Organizing Committee, local organizing committee>> organize the RoboCup event for all leagues.

==== 実行委員会/Executive Committee
実行委員会の委員は小型機リーグの長期的目標を担当しており、RoboCup委員会だけでなく、他のリーグとの提携も行っている。実行委員会は小型機リーグとその成果を毎年RoboCup委員会に報告し、リーグを組織するためのフィードバッグを得る。実行委員会の委員はRoboCup委員会の理事会によって選出される。委員は3年間の任期を務める。 +
Executive committee members are responsible for the long term goals of the Small Size League and thus have also contact to other leagues as well as to the RoboCup federation. The executive committee presents the Small Size League and its achievements to the RoboCup federation every year and gets feedback to organize the league. Executive committee members are elected by the board of trustees of the RoboCup federation. They serve 3-year terms.

==== 技術委員会/Technical Committee
小型機リーグの技術委員会はルールや共有ソフトウェアのような技術的な側面を担当している。すべての委員は前回大会に参加したチームのチームリーダー達によって選出される。 +
The technical committee of the Small Size League is responsible for the technical aspects of the RoboCup, such as maintaining the rules and the shared software. All members are elected by the team leaders of the teams which have participated in the previous competition.

==== 組織委員会/Organizing Committee
小型機リーグの組織委員会は競技会の準備と組織を担当している。これにはスケジュールの作成、予選リーグの評価方法、競技の進行が含まれている。技術委員会の委員はロボカップの受託者(RoboCup trusteesの訳がわからない)とリーグの(実行委員会/executive committeeによって選出される。 +
The organizing committee of the Small Size League is responsible for preparing and organizing the competition. This mainly includes making the schedule, performing the qualification process, and running the competition. The committee members are selected by the <<Executive Committee, executive committee>> of the league and the RoboCup trustees.

==== 地域の組織委員会/Local Organizing Committee
地域の組織委員会は異なるリーグのニーズに応じてイベントを計画して実行する事を担当している。これには、チームエリア（フィールド、ネットワーク、テーブル、ホワイトボード、スクリーンなど）の設定、イベントのスケジュールの作成、安全性とセキュリティのコンセプトの実装が含まれる。 +
The local organizing committee is responsible for planning and executing the event itself in accordance with the needs of the different leagues. This includes setting up the team areas (fields, network, tables, whiteboard, screens, etc.), creating a schedule for the event and implementing a safety and security concept.

=== ディヴィジョン/Divisions
小型リーグではDivision AとDivision Bと呼ばれる2つの分けられたトーナメントによるDivisionを提供する。Division Aは先進的なチームを対象として、それ以外の新しいチームと競争力が弱いチームはDivision Bで試合をすることができる。各チームは2つのDivisionのうち1つのみに参加することができる。 +
The Small Size League is divided into two divisions with separate tournaments, namely division A and division B. Division A is aimed at advanced teams whereas new and/or less competitive teams can play in division B. Each team will only play in one of those two divisions.

予選で使う資料を提出する時、各チームは簡潔な理由をつけてどちらのDivisionで競技したいかも選択すること。組織委員会/organizing committeeのメンバーは最終的な決定をする。予選の方法に関する情報はRoboCup Small Size Leagueの公式ウェブサイト(https://ssl.robocup.org) で確認できる。 +
When submitting the qualification material, the team also chooses a preferred division including a short rationale. The members of the <<Organizing Committee, organizing committee>> will have the final word. Information about the qualification process can be found on the official RoboCup Small Size League website (https://ssl.robocup.org).

二つのディビジョンの違いに関する要約は付録/Appendixで確認できる。 +
A summary of differences between the two divisions can be found in the <<Differences Between Divisions, Appendix>>.

NOTE: Division制を導入することによって、新しいチームの参入障壁を大幅に引き上げることなく、小型機リーグのより急速な進歩を可能にする。また、ディビジョンの導入によって、同じ強さのチームとの試合を大幅に増やすことができる。 +
Divisions allow for more radical advancements in the Small Size League without drastically raising the entry barrier for new teams. Additionally, they also considerably increase the amount of matches between teams of similar skill.
