== 得点/Scoring Goals
ボールがゴールポストの間に入ってゴールした場合には、得点したチームがその直前のプレイにおいていかなるルール違反も犯していないことを条件に得点が認められる。 +
A team scores a goal when the ball fully enters the opponent goal between the goal posts,
provided that:

* The team did not exceed the allowed number of robots when the ball entered the goal.
* The height of the ball did not exceed 0.15 meters after the last touch of the teams robots.
* The team did not commit any <<Non Stopping Fouls, non stopping foul>> since the teams robots last touched the ball.

NOTE: "The team" refers to the scoring team that is awarded a goal, not the team that kicked the ball.
For example, an own goal is not possible while the opponent team has too many robots on the field.

NOTE: <<ペナルティーキック/Penalty Kick, ペナルティーキック>>の間は、より詳細なルールが適用される。 +
During <<ペナルティーキック/Penalty Kick, penalty kicks>>, more specific rules apply.

ゴールが無効とみなされた場合、試合はボールがゴールの外側のゴールラインを交差したものとして継続する。 +
If the goal is considered invalid, the game will be continued as if the ball crossed the goal line outside the goal.
