== 得点/Scoring Goals
ボールがゴールポストの間に入ってゴールした場合にゴールの得点が認められる。ただし、インプレイに入った後にゴールを得点したチームがいかなるルール違反も犯していないことを条件とする。 +
A goal is scored if the ball enters the goal between the goal posts, provided that no rule infringement has been committed in the play immediately preceding this event, by the team scoring the goal.

さらに、ゴールは以下の場合のみ有効である。 +
Additionally, the goal is only valid if

* アタッカーが最後にボールに触れてから、ボールの高さが0.15mを超えていない +
The height of the ball did not exceed 0.15 meters after the last touch of an attacker.
* ゴール時のキックが行われた時点でのボール位置は、相手チームのディフェンスエリア内ではない +
The ball was not located in the opponent defense area when the goal kick started.
* ゴール時のキックにおいて、ボール速度は制限を超えていない +
The ball did not exceed the ball speed limit during the goal kick.

NOTE: <<ペナルティーキック/Penalty Kick, ペナルティーキック>>の間は、より詳細なルールが適用される。 +
During <<ペナルティーキック/Penalty Kick, penalty kicks>>, more specific rules apply.

ゴールが無効とみなされた場合、試合はボールがゴールの外側のゴールラインを交差したものとして継続する。 +
If the goal is considered invalid, the game will be continued as if the ball crossed the goal line outside the goal.
