== シュートアウト/Shoot-Out
.定義/Definition
両チームが交互にゴールに得点を決めようと各チームそれぞれ5回のシュートを試行する。もし両チームとも5回の試行が終わった時に同点であった場合、2チームの得点が異なるまで前と同じ順番でさらに試行回数を増やす。 +
Both teams alternately attempt to score a goal until each team has performed 5 attempts. If both teams have the same score after those 5 attempts, each team takes another attempt in the same order as before until the score of the two teams is different.

各チームには1台の攻撃ロボットと1台のキーパーだけが許可される。シュートアウトの間、攻撃ロボットと相手のキーパーだけがボールの操作と移動ができる。他のロボットは干渉してはいけない。 +
Only one attacking robot and one keeper is allowed per team. During a shoot-out attempt, the attacking robot and the opponent keeper are the only ones allowed to move and <<Ball Manipulation, manipulate the ball>>. Other robots are not allowed to interfere.

シュートアウトの手順は以下である: +
The procedure of a shoot-out attempt is as follows:

. ボールは相手のゴールから(ディヴィジョンAなら)8mか(ディヴィジョンBなら)6mの位置にあるミッドライン(ハーフウェイラインではない)に人間の審判によって置かれる。(The ball is placed by the human referee on the <<Additional Lines, mid-line>> (not halfway line), 8 meters (division A) or 6 meters (division B) away from the opponent goal.)
. ペナルティーキックのコマンドが発行されたとき、守備側チームのキーパーはゴールラインに移動し、ラインに触れ続けなければならない(When the <<Penalty Kick, penalty>> command is issued, the defending keeper has to move to the goal line and keep touching it.)
. normal startのコマンドが発行されたとき、アタッカーはボールを操作することが許可される。ボールは相手ゴールに向かって動かさなければならない。これは、SSL-Visionの座標系におけるx座標によって測定されている。(When the <<Normal Start, normal start>> command is issued, the attacker is allowed to <<Ball Manipulation, manipulate the ball>>. The ball has to only move towards the opponent goal, as measured by its x coordinate in the coordinate system of <<Vision, SSL-Vision>>.)
. ボールがインプレイになった時、守備側チームのキーパはペナルティキックと同じように再び自由に動いてよい。(When the ball is <<Ball In And Out Of Play, in play>>, the defending keeper may move freely again, analogous to a <<Penalty Kick, penalty kick>>.)

以下の場合に得点が与えられる: +
A goal is awarded if:

* normal startのコマンドが発行されてから10秒以内に守備側チームのゴールの地面もしくはゴールウォールの内面にボールが接触した。(the ball touches the inner surface of a goal wall or the ground of the goal of the defending team in less than 10 seconds, starting from when the <<Normal Start, normal start>> command is issued)
* 守備側チームがいかなる違反も犯していない(the defending team violates any rule)

以下の場合に得点が与えられない: +
A goal is not awarded if:

* ボールがゴールより外側のいずれかのフィールドラインを横切った(the ball crosses any <<Field Lines, field lines>> outside the goal)
* 守備側チームのキーパーが2次元空間内で少なくとも90°以上ボールの速度ベクトルを変えるようにボールに触れる(the defending keeper touches the ball such that the ball speed vector changes direction by at least 90 degrees in 2D space)
* 攻撃側チームが何らかの違反を犯した(the attacking team violates any rule)

NOTE: ゴールの得点のために定義された制限はここでは適用されない。これには0.15mのボールの高さ制限も含まれる。例えばドリブルの超過なども該当する。(The restrictions defined for <<Scoring Goals, scoring goals>> do not apply here. This explicitly includes the ball height limit of 0.15 meters. Other rules like the <<Excessive Dribbling, excessive dribbling>> limitation for example do.)

ロボットはシュートアウトの間に交代してもよい。新しいロボットを即時入れても良い。 +
Robots may be <<Robot Substitution, substituted>> between shoot-out attempts. The new robot may be put in right away.

NOTE: シュートアウト中はタイムアウトは許可されていない事に注意する事。 +
Note that <<Timeouts, timeouts>> are not allowed during shoot-out.

.用途/Usage
シュートアウトは直前のゲームステージで両チームが同じ点の場合に、予選の勝者を決定するために使用される。 +
Shoot-Out is used to determine the winner of an elimination match if both teams scored the same amount of goals in previous <<Game Stages, game stages>>.

